### PR TITLE
The after save form control should be a radio instead of a checkbox

### PR DESCRIPTION
**Pull request by shacky**

### CODE REVIEW

**Comment by shacky** [comment]
I added the "back" radio as the default one because we couldn't deselect a radio after selection.

**Comment by laradocs** [comment]
You can custom extends class to custom files.

**Comment by shacky** [comment]
If there are checkboxes a user can check a couple of them. This doesn't have a sense - don't you think?

**Comment by laradocs** [comment]
You're right, but I don't entirely agree.
If you want to cancel after choosing it, you can only refresh the browser and the filled form will disappear.
We can't force users to do something, hope you can understand.
Thanks for your suggestions and contributions!

**Comment by shacky** [comment]
Ok, so give me an example why use checkboxes here instead of radios? The difference is radio is a single selection and a checkbox is multi-selection. How to use multi-selection here? You cannot - so I made a pull request to change it to radios.

Just in case to know we are talking about the same feature - model edit/create form:
- without patch:
checkboxes
- after my patch:
radios

**Comment by shacky** [comment]
> If you want to cancel after choosing it, you can only refresh the browser and the filled form will disappear.

I think we are not on the same page - the "back" option in my version works after submitting the form and it is the default action taken after the form submit (it goes back to the previous page). The same as without any of the checkboxes selected in the original version.

**Comment by laradocs** [comment]
I don't think it's necessary to make some trivial changes

Thanks for your contributions!

**Pull request closed without merging**
