### PR TITLE
add missing flags font

### PR DESCRIPTION
**Pull request by shacky**
There are references in CSS files, but SVG files were missing

### CODE REVIEW

**Comment by jqhph** [comment]
What files are the icons referenced in? The flags font  was deliberately deleted by me

**Comment by shacky** [comment]
resources/assets/dcat/plugins/vendors(-rtl|).min.css
resources/dist/dcat/plugins/vendors(-rtl|).min.css
What is more, these files have a header that is from a paid template - isn't it? We should fix it by cleaning code from such things if we don't use that template.

There are also references in your docs: http://www.dcatadmin.com/docs/2.x/custom-navbar.html

**Comment by jqhph** [comment]
Yes, the old version was using vuexy，I will delete these codes，thanks for the report

**Comment by shacky** [comment]
resources/assets/sass/bootstrap-extended/_forms.scss - there is also vuexy reference
```
/* Vuexy Custom Checkbox */
.vs-checkbox-con{
```

**Pull request closed without merging**
